apiVersion: v1
kind: Service
metadata:
  name: {{ template "service.fullname" . }}
  labels:
    app: {{ template "service.name" . }}
    chart: {{ template "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: {{ .Values.image.webPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.image.grpcPort }}
      protocol: TCP
      name: grpc
  selector:
    app: {{ template "service.name" . }}
    release: {{ .Release.Name }}
